Repository release-it-plugins/lerna-changelog, pull requests merged in 2022-07, with the labels that each got.

#208 Fix compatibility with `release-it` v15
  .eslintrc.cjs
  .github/workflows/ci.yml
  index.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  test.js
Labels: breaking

#222 Move test to __tests__ directory
  .eslintrc.cjs
  __tests__/plugin-test.js
Labels: internal

#223 Bumps release-it to include fixed exports
  .github/workflows/ci.yml
  __tests__/plugin-test.js
  package-lock.json
  package.json
Labels: bug

#224 Renames package to @release-it-plugins/lerna-changelog
  README.md
  __tests__/plugin-test.js
  index.js
  package-lock.json
  package.json
Labels: enhancement
