Repository release-it-plugins/lerna-changelog, pull requests merged in 2024-05, with the labels that each got.

#301 Replace lodash.template package with lodash itself due to advisory
  index.js
  package-lock.json
  package.json
Labels: security

#303 Fixes lodash import that isn't playing nice with ESM
  index.js
Labels: bug

#304 Upgrades ci workflow to use node@18, upgrades action versions
  .github/workflows/ci.yml
Labels: internal
